controller/documentcontroller.php

Minor fix to a missing argument.

Pass fileId to get path

---

appinfo/routes.php
controller/documentcontroller.php
js/documents.js
lib/db/wopi.php

This adds support for WOPI CheckFileInfo API.

Wopi fileinfo

---

js/documents.js

... since we save to disk on abnormal client termination.

Do not show scary warning dialog

---

appinfo/app.php
controller/documentcontroller.php
css/viewer/odfviewer.css
js/viewer/viewer.js

... to add new odf files from main 'Files' app

Use new owncloud9 addMenuEntry plugin

---

Makefile

It is being used by addMenuEntry plugin in owncloud9

package odfviewer.css too

---

.gitignore
Makefile
appinfo/database.xml
controller/documentcontroller.php
css/style.css
js/documents.js
lib/db/wopi.php
lib/storage.php

... alongwith other minor fixes that I found on the way.

Revision history sidebar

---

js/documents.js

404 slowserver

---

appinfo/info.xml.in

Adds the OCS ID for https://apps.owncloud.com/content/show.php/Collabora+Online+connector?content=174727

Add OCS ID

---

lib/db/wopi.php

On my setup this is needed to load a document
Maybe related to using postgres

Use non strict comparison to validate token

---

js/documents.js
templates/documents.php

Ports https://github.com/owncloud/documents/pull/652 by @vicdeo to richdocuments
cc @pranavk @kendy @rullzer @Guillaume99 @mar1u5 
This fixes nextcloud/server#999
Also fixes this error message:
```
Could not find resource file "/apps/files/js/jquery.iframe-transport.js"
```

Fix upload in richdocuments

---

.travis.yml

Not anymore supported in Nc and oC master.

Disable builds for 5.4 and 5.5

---

controller/documentcontroller.php
js/documents.js

Don't assume that the action name is 'edit' all the time. Instead, if
it's view, then initialize leaflet with permission=readonly.

bccu#2033 Respect WOPI action names

---

appinfo/app.php

There are no personal settings

---

img/app.svg

Otherwise the icon is shown too small in the app management. Please review @LukasReschke @MorrisJobke @timar @pranavk

add viewBox attribute to icon so it shows correctly in the app management

---

appinfo/database.xml
appinfo/info.xml
controller/documentcontroller.php
controller/sessioncontroller.php
js/documents.js
lib/db/wopi.php
templates/documents.php

Also fixes couple of things. Worth mentioning is that now if you set the permission of a file from owncloud sidebar to 'view', it would respect it and the view would be opened in readonly mode only.
Token field is now indexed, so hope there would be some performance improvement.

Add UserCanWrite WOPI property

---

js/share.js

Just like for core, cause it’s also possible to share with other servers. Please review @timar @pranavk @LukasReschke

use Federated Cloud ID wording

---

js/documents.js

We probably want to remove the app view completely in future. This is
just a quick hack.

OC.Upload is now OC.Uploader in OC 10

---

controller/documentcontroller.php

See https://github.com/nextcloud/richdocuments/pull/52 for details. Idea
is same.

Support encrypted documents

---

controller/documentcontroller.php

... otherwise, we return incorrect timestamp in PutFile response, which leads to some unexpected behavior in wsd.

Get file mtime before logging out

---

appinfo/database.xml
appinfo/info.xml

Use bigint for fileid

---

controller/documentcontroller.php

Also store the mtime before logging out. Otherwise the timestamp which is sent to the WOPI client is different from the actual timestamp.
This fixes the spurious 'Document has changed' dialog.

Use user's root folder to get mtime etc.

---

appinfo/app.php
appinfo/application.php

- add to config.php
```php
'collabora_group' => 'collabora'
```
- see collabora in the menu for users which are in this group
- users which are not in this group will not see collabora in the menu

Add group limiting function.

---

js/documents.js

Start listening for standard revision history WOPI message

---

controller/documentcontroller.php
controller/settingscontroller.php
lib/db/wopi.php

This cleans up the code a bit and adds support for editing documents on samba storage.

Samba server support

---

README.md

This PR adds note to the README on how to setup working development Collabora instance in few steps, without the need to have any advanced configurations/deployments relying on SSL configuration.
cc @DeepDiver1975 @VicDeo

Add note on Developer guidelines

---

appinfo/info.xml

Bump max-version to 10 for semver

---

appinfo/routes.php
js/documents.js
js/viewer/viewer.js
lib/Controller/DocumentController.php

Fixes https://github.com/owncloud/richdocuments/issues/238:
- return from normal and shared with user/group documents
- return from shared by link for both folder and file share
CC @pmaier1 @DeepDiver1975 @PVince81

Fix return to document from Collabora Editor

---

Makefile

Part of issue https://github.com/owncloud/QA/issues/609

Remove old reference to composer.phar in Makefile

---

composer.lock
lib/Db/Storage.php
phpunit.xml
tests/unit/Controller/DocumentControllerTest.php

1) phpunit enable failOnRisky failOnWarning 
2) remove unused use statements 
3) Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0)

Phpunit 5 6

---

.drone.yml
Makefile
phpcs.xml
tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/SecureViewContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/AdminAdditionalSettingsPage.php
tests/acceptance/features/webUISecureView/main.feature
vendor-bin/behat/composer.json
vendor-bin/php_codesniffer/composer.json

This adds a secure view tests for the richdocuments.

Add tests for secure view

---

tests/acceptance/features/bootstrap/SecureViewContext.php

Some steps that are essential are ported  to ```core```  from ```richdocuments``` app in this pr https://github.com/owncloud/core/pull/35890. So, now these steps are redundant in ```richdocuments``` app and hence removed.
https://github.com/owncloud/core/issues/35845
CI

removing of steps that already exists in core

---

.drone.yml
tests/acceptance/features/webUISecureView/main.feature

Issue https://github.com/owncloud/core/issues/35777
The old core `stable10` is now `master`

Remove stable10 test jobs

---

tests/acceptance/features/webUISecureView/main.feature

Adds acceptance test for resharing when secured view is enabled.
https://github.com/owncloud/richdocuments/issues/265
CI

secure view test for resharing

---

appinfo/Migrations/Version20190710194710.php
appinfo/info.xml

Fixes https://github.com/owncloud/richdocuments/issues/261 @skshetry

Adjust fileid to bigint

---

tests/acceptance/features/webUISecureView/main.feature

```@issue-3441``` changed to ``` @issue-enterprise-3441```

issue name fixed

---

js/viewer/shareoptions.js

Fixes https://github.com/owncloud/richdocuments/issues/283

[283] Make sure to register attributes only for supported mimetypes

---

.drone.starlark
.drone.yml
composer.json
composer.lock
phpunit.xml
tests/unit/AppInfo/ApplicationTest.php
tests/unit/Controller/DocumentControllerTest.php
vendor-bin/behat/composer.json

Similar to https://github.com/owncloud/configreport/pull/121

Adjust tests

---

vendor-bin/behat/composer.json

Needed because of owncloud/core#36999

[Tests-only] Update guzzle for testing to 6.5

---

.drone.star

This reverts commit 153e47638bed46bd1c7dde25487a5be5f7855f62.
Fixes issue #319

Revert "do not run acceptance tests against 'latest' 10.3.2 server"

---

.drone.star
lib/AppConfig.php
lib/AppInfo/Application.php
lib/Controller/DocumentController.php
lib/Controller/SettingsController.php
lib/Db.php
lib/Db/Wopi.php
lib/Helper.php
lib/Http/DownloadResponse.php
lib/Storage.php
phpstan.neon
vendor-bin/phpstan/composer.json

Related - owncloud/QA#642
Update phpstan to 0.12

[Tests-Only] Update phpstan to latest version

---

tests/acceptance/features/webUISecureView/main.feature

Refactor acceptance tests.
- Fixes: https://github.com/owncloud/richdocuments/issues/340

[Tests-Only] Refactor acceptance tests for rich documents app

---

lib/Controller/DocumentController.php

Signed-off-by: Muhammet Kara <muhammet.kara@collabora.com>

Avoid guzzle for discovering built-in CODE server

---

.drone.star
appinfo/info.xml
lib/AppConfig.php
lib/AppInfo/Application.php
tests/unit/AppConfigTest.php

- Switch to new license manager
- Raise minimum dependency to 10.5
@pmaier1

Switch to new license Manager

---

js/viewer/viewer.js

Fixes https://github.com/owncloud/richdocuments/issues/369

Context menu register calls an deprecated function, displayName "edit" is not specific

---

lib/AppInfo/Application.php
lib/Controller/DocumentController.php
tests/unit/Controller/DocumentControllerTest.php

fixes https://github.com/owncloud/enterprise/issues/4279

Make sure to check IUser directly for IGroup->inGroup

---

README.md
js/viewer/viewer.js
lib/AppConfig.php
lib/Controller/DocumentController.php
templates/admin.php

- update documentation
- properly handle error when creating file
- fixes https://github.com/owncloud/appliance/issues/94 -> remove default wopi_url and use hint instead (important for appliance installation @voroyam )

Minor bugfixes

---

lib/Controller/DocumentController.php

Context: when collaborating on the file, only 1st read operation is being performed (for the user opening the document). Next readers were opening directly the editor.
This PR adds read operation when aquiring token for a user.
Tested:
- make sure audit log is triggered 
fixes https://github.com/owncloud/enterprise/issues/4290

make sure accessing a file triggers auditable read operation

---

appinfo/info.xml
lib/AppConfig.php
templates/admin.php
tests/acceptance/features/webUISecureView/main.feature
tests/unit/AppConfigTest.php

Requires https://github.com/owncloud/core/pull/37813 (planned for OC 10.6).
It might need an additional version change.
Minimum version of the app increased.

[OC 10.6] Proper license fix

---

tests/acceptance/features/webUISecureView/main.feature

like was done in core last week.
Fixes CI

[tests-only] Specify skeleton in tests

---

lib/Storage.php

https://github.com/owncloud/richdocuments/issues/385

Fix Public Links shared from Local Storage

---

js/documents.js

Only possible color that can be sent to COOL
from the existing theme looks header bg color
Signed-off-by: Mert Tumer <mert.tumer@collabora.com>

Implemented possibility of theming COOL.

---

.phan/config.php
vendor-bin/phan/composer.json

https://github.com/phan/phan/releases/tag/4.0.0
A new major version of phan was released a while ago. It supports PHP 7.2, 7.3, 7.4 and 8.0. Use it.

[test] Bump phan analysis to v4.0

---

CHANGELOG.md
appinfo/info.xml

merge back branch release-2.5.0

---

css/viewer/odfviewer.css
img/app-dark.svg
js/viewer/viewer.js

Use app icon for Open in Collabora action

---

lib/Controller/DocumentController.php

Warning was too harsh, so changed it in favour of debug.

Replace logger warning with logger debug on put

---

tests/acceptance/features/bootstrap/SecureViewContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/AdminAdditionalSettingsPage.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only] enforce strict type checking in acceptace tests code

---

js/documents.js
templates/documents.php

Upload in rich documents office overview stopped working, fixed with this change. 
Fixes:
- https://github.com/owncloud/enterprise/issues/4869#event-5770193716

Make upload work again

---

css/viewer/odfviewer.css
js/viewer/viewer.js
lib/Controller/DocumentController.php

Signed-off-by: Mert Tumer <mert.tumer@collabora.com>

added Diagram document type to + button

---

README.md

Last element has no comma in json

---

js/admin.js

fixes https://github.com/owncloud/richdocuments/issues/448

fix enable open action with secure view default checkbox

---

lib/AppConfig.php
lib/AppInfo/Application.php
lib/Controller/DocumentController.php
lib/Controller/SettingsController.php
tests/unit/AppConfigTest.php

fixes https://github.com/owncloud/richdocuments/issues/442

disable secure view js and settings when not available

---

css/style.css
js/documents.js
js/viewer/viewer.js
templates/documents.php

fixes https://github.com/owncloud/richdocuments/issues/444

ensure ODG Drawing compatibility across integration

---

js/web/app.js
js/web/richdocuments.js

Signed-off-by: Mert Tumer <mert.tumer@collabora.com>

web: add Drawing filetype and add it to + menu

---

lib/Controller/DocumentController.php
lib/Storage.php

Fixes issue #460 and gets CI green again.

Adjust 'if' conditionals that were reported by phpstan

---

tests/acceptance/features/webUISecureView/main.feature

Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:

[full-ci] [tests-only] Refactored inter scenarios space

---

.drone.star

This reverts commit b73781c50d2eec4629db748ba1ac0bbec11c7cc2.
Issue https://github.com/owncloud/QA/issues/746

[tests-only] [full-ci] Revert "Do not test against core latest 10.10 any more"

---

js/documents.js
lib/AppInfo/Application.php
lib/Controller/DocumentController.php
lib/DocumentService.php
lib/FileService.php
tests/unit/DocumentServiceTest.php

fixes https://github.com/owncloud/enterprise/issues/5729

make sure to retrieve correct supershare based on current dir context

---

js/documents.js
lib/Controller/DocumentController.php
lib/DiscoveryService.php
lib/DocumentService.php
templates/documents.php
tests/unit/DiscoveryServiceTest.php
tests/unit/DocumentServiceTest.php

handle federated share mount to display error and further refactor

---

tests/acceptance/features/webUISecureView/main.feature

Part of: owncloud/QA#825
> Note: This PR was made by an automated script, in case something is not right I'll take care of it manually.

[tests-only] fix the line syntax

---

CHANGELOG.md
appinfo/info.xml
css/style.css
js/documents.js
sonar-project.properties

Closes #501 
Thanks to @timar for your great teamwork!

Merge back release 4.0.0 branch to master

---

appinfo/routes.php
js/documents.js
lib/Controller/DocumentController.php
lib/Controller/DocumentRevisionController.php
lib/Controller/OCSFederationController.php
lib/Controller/WopiController.php
lib/Db/Wopi.php
lib/DocumentService.php
lib/FileService.php
tests/unit/Controller/DocumentRevisionControllerTest.php
tests/unit/Db/WopiTest.php
tests/unit/FileServiceTest.php

fixes: https://github.com/owncloud/richdocuments/issues/415 , https://github.com/owncloud/richdocuments/issues/222
I attempted to do it in such a way that it does not affect code complexity and performance of the "non-versioned" code paths. Thus performance is affected only when versions are listed or accessed

Bugfix: broken version revision

---

js/settings-personal.js
lib/Controller/WopiController.php
lib/Panels/Personal.php
templates/settings-admin.php
templates/settings-personal.php

Fixes: 
- https://github.com/owncloud/richdocuments/issues/527
- https://github.com/owncloud/richdocuments/issues/528
Screenshot for new input handling

Zotero fixes for 4.1.0rc 

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

build: prepare release 4.2.0
