js/documents.js

"Download as" links in File menu are downloading files with a different filename like `ccs-fileID.ext`. 
With this commit CloudSuite preserves original filenames when downloads them.

Fix "Download as ..." for wrong filenames

---

owncloud-collabora-online.spec.in

+ it does not require loleaflet and loolwsd, because
loolwsd server can run on a separate machine, and
loleaflet will be served by loolwsd in the near
future.
+ it requires php5-apcu and the following line should be
inserted to owncloud/config/config.php:
'memcache.local' => '\OC\Memcache\APCu',

rpm package requirements update

---

js/documents.js

Use filename as additional param to let the child frame know the
name of the document easily.
Use closebutton param to instruct the child frame about whether
to show the close button, or not.

Use window.postMessage API for cross-domain frame communication

---

lib/db/wopi.php

syntax error, unexpected '*', expecting ',' or ';' at /var/www/owncloud/apps/richdocuments/lib/db/wopi.php#28

PHP syntax error on Ubuntu 14.04 LTS

---

owncloud-collabora-online.spec.in

It is for CODE VM, possibly openSUSE specific.

set default WOPI Client URL for rpm

---

js/documents.js

This is mainly problem in firefox where sometime, key press
events are handled by the browser, but we do not want that.

give focus explicitly to loleafletframe after loading

---

appinfo/info.xml.in
lib/storage.php

Due to API change (searchByMime), app was completely broken when
installed with owncloud9. This change should make it work with
owncloud9, while still keeping older owncloud version (upto 8.2)
in working state.
Lets use functions on object returned by searchByMime instead of
directly accessing its data members.

Make me work with owncloud9

---

js/documents.js

Route /close/ doesn't mean anything, and we were making this
additional call always before closing the document. This had a
side-effect that sometimes /close/ call would be processed after
we assign returnToDir to window.location making browser always
stuck in richdocuments#index rather than reeturnToDir. This was
mainly the problem in firefox with owncloud9

bccu#1882: Return to where user started by removing redundant call

---

js/documents.js

... since loleaflet explicitly requires it now if revision
history option is required.

Explicitly ask for revision history option

---

appinfo/app.php

Registers the JS via event dispatchers. Otherwise the JS is not loaded when somebody has pretty URLs configured.

Use event dispatcher

---

.gitignore
appinfo/info.xml

When developing apps for Nextcloud it is more usual that as a developer you can directly clone the app and enable it. The makefile is also very specific.
To improve the developer experience I have renamed that file to "info.xml" directly. At least I was kinda confused why I couldn't enable the app the first time I cloned it :-)

Name file info.xml directly

---

appinfo/info.xml

The long title »Collabora Online« doesn’t fit in the app dropdown and is longer than all the other app titles. Also, »Online« is a bit obvious here. ;)
Please review @timar @pranavk @karlitschek @LukasReschke – the main question is if it’s fine from a branding point of view.

update name to fit in the app dropdown

---

appinfo/application.php
controller/documentcontroller.php
tests/controller/documentcontrollertest.php

Support for default settings when there is none provided by user
was already in lib/appconfig.php
But we were using the CoreConfig object always which queries the
database; lets use the appConfig object so that if the value is
missing in the database, we still have the default value to take
care of the app.

Respect default settings

---

js/documents.js

Be consistent with owncloud own version sidebar, and loleaflet's
DocumentRepair dialog.

Show relative timestamps as heading, formatted as tooltip

---

appinfo/database.xml
appinfo/info.xml
controller/documentcontroller.php
js/documents.js
lib/db/wopi.php

Adds a new property PostMessageOrigin to WOPI's CheckFileInfo.
The inner frame then only sends message to target with origin
mentioned in this property.
Also implement editor initialization WOPI specs. Inner frame
sends a App_LoadingStatus message to us when ready, and we send
Host_PostmessageReady when we are ready.

security: Support WOPI's PostMessageOrigin

---

controller/documentcontroller.php

'OwnerId' is a required property (http://wopi.readthedocs.io/projects/wopirest/en/latest/files/CheckFileInfo.html#required-response-properties).
Microsoft Office Online won't work without this property. :)

Missing response property

---

controller/documentcontroller.php

... otherwise for DB backends like MariaDB, false gets converted to ''

Cast updatable to int

---

js/viewer/viewer.js

Also simplify the logic during file action registration. Basically, we
should try to open all known mimetypes; file permissions are taken care
of later in the WOPI protocol.
Without this commit, it is not possible to open a document in a
directory for which user has no write access.

Try opening readonly documents too

---

controller/documentcontroller.php

No idea why we had a complicated CSP set here. This CSP is being set for
the owncloud frame and is not going to affect the LibreOffice Online
iframe. Lets simplify here.

Remove superfluous CSP

---

controller/documentcontroller.php

Without this, files revisions are only looked in root directory which is
certainly incorrect.

Fix revision history path

---

controller/documentcontroller.php

This is used to uniquely identify a host even when
documents are accessed from alias hostnames.

WOPI CheckFileInfo now returns a host-specific unique ID

---

controller/documentcontroller.php
lib/helper.php

This is a WOPI extension to detect any external document change. For
example, when the file that is already opened by LOOL is changed (for
example, using upload mechanism or any other way).
The WOPI host (OwnCloud) sends LastModifiedTime (in WOPI specs) as part
of the CheckFileInfo response. It also expects WOPI client to send the
same timestamp in X-LOOL-WOPI-Timestamp header during WOPI::PutFile. If
this header is present, then WOPI host checks, before saving the
document, if the timestamp in the header is equal to the timestamp of
the file in its storage. Only upon meeting this condition, it saves the
file back to storage, otherwise it informs WOPI client about some change
to the document.
WOPI client is supposed to inform the user accordingly. If user is okay
with over-writing the …

Include support for X-LOOL-WOPI-Timestamp

---

controller/documentcontroller.php
controller/settingscontroller.php
js/admin.js
js/documents.js
templates/admin.php
templates/documents.php

This is useful when the same owncloud instance is accessed by multiple
URLs. It is important that we feed same URL to Collabora Online for the
same document otherwise collaborative editing wouldn't be possible.
This is especially useful in case of authentication mechanisms like
Shibboleth where some URLs are protected. Collabora
Online cannot access such URLs; by providing canonical webroot we feed
only the accessible URL to Collabora Online.
Eg: Same owncloud instance accessed by /owncloud and /owncloud-shib
(only latter protected by shibboleth).
In this case, one should put /owncloud as the Canonical webroot in
Collabora Online settings.

Add support for adding canonical webroot

---

controller/documentcontroller.php

Otherwise we cannot set the content security policy correctly.

Strip the service root prefixes in the Collabora Online wopi_url.

---

appinfo/Migrations/Version20190623184232.php
appinfo/info.xml
lib/AppConfig.php
lib/Controller/DocumentController.php
lib/Controller/SettingsController.php
lib/Db/Wopi.php
lib/Http/DownloadResponse.php
templates/admin.php

There were few problem with previous implementation:
- with encryption or without, all activity was not auditable (incognito mode by default)
- public link was set for editor as owner of the file
- non-uniform method for getting priviledged access to file from collabora
- it was not made clear to the admin that this app is "partially" compatible with user key encryption as this app requires priviledged access to the files (and password of user with which files are encrypted cannot retrieved)
This PR fixes it:
Tested:

Make master encryption compatible with audit/activity

---

js/viewer/shareoptions.js
lib/Controller/DocumentController.php
lib/Db/Wopi.php
tests/acceptance/features/webUISecureView/main.feature

Do not allow to open document in Collabora if both download and viewing (e.g. with watermark) is disabled. 
Cases considered:
- user receives a share with `download->false` and `view-with-watermark->true`: user can view (with watermark) the file in the editor, but cannot download to disk. 
- user receives a share with `download->false` and `view-with-watermark->false`: user cannot view the file nor download to disk (insufficient permission exception)
- user receives a share with `view-with-watermark->false`:  user cannot open editor due to viewing restriction being set to false (insufficient permission exception)
- user receives a share with `download->false`:  user can open editor with no watermark, but cannot export/download file

Do not allow to open document if viewing is disabled

---

js/admin.js
templates/admin.php

Fixes https://github.com/owncloud/richdocuments/issues/288

[288] Hide instead of check settings print button without secure view

---

Makefile

fixes issue #300 
1) remove other various CI and code-analysis-related files for the `make appstore` tarball.
2) remove little rubbish from `l10n` folder for the `make dist` tarball.
This gets the 2  tarballs to have the same contents.

Align contents of tarball from 'make appstore' and 'make dist'

---

tests/acceptance/features/webUISecureView/main.feature

Resharing in secure view is disabled according to this PR https://github.com/owncloud/core/pull/36265 .
This PR adjusts the previous acceptance test in accordance with the disabling of reshare in secure view.
- Fixes https://github.com/owncloud/richdocuments/issues/308
- On top of https://github.com/owncloud/core/pull/36628

Acceptance test: resharing is disabled in secure view

---

js/viewer/shareoptions.js
tests/acceptance/features/webUISecureView/main.feature

Update share can update any field in share interface separately. This MR ensures that attributes get updated only if attribute or permission fields got updated.

Do not update permissions or attributes if other share fields gets updated

---

Makefile

PR #318 moved `.drone.starlark` to `.drone.star` but missed that it was mentioned in `Makefile`
Adjust `Makefile`
(there does not seem to be a `release-2.3.0` branch in this repo, so this PR is to `master`)

Exclude drone.star from release tarball

---

appinfo/info.xml
lib/BackgroundJob/CleanupExpiredWopiTokens.php
lib/Controller/DocumentController.php
lib/Db/Wopi.php
tests/unit/BackgroundJob/CleanupExpiredWopiTokensTest.php

No need to hold expired tokens in database, this pr adds a background job for cleaning those tokens.
Fixes #https://github.com/owncloud/enterprise/issues/3732

add a background job for deleting expired tokens

---

lib/Controller/DocumentController.php
templates/documents.php

Fix https://github.com/owncloud/enterprise/issues/3723 by using a custom header without any button in it. This custom header will be used only in public links, while normal accesses for registered users will use the normal header.

Remove header's buttons when the file is accessed through public link

---

tests/acceptance/features/webUISecureView/main.feature

The core acceptance test code now checks more that a file/folder really is a file/folder. A step was wrong here - fix it.

[Tests-Only] Adjust test step to expect a folder

---

.drone.star

This reverts commit 63c9b3625cf0d1aa6cbf0f0bbdc97336308e3d6c.
core `latest` is now a 10.5.0 tarball, so we can test against it.
Note: while resolving conflicts for this revert, I have also effectively reverted https://github.com/owncloud/richdocuments/commit/9bdb5c2b2731180f3ce7bc07f2e8f73e7e370726 and sorted out removing the specific `servers` list from `acceptance` `webUI` - the list that we want is already the default.

[Tests-Only] Revert "Only run acceptance tests PHP 7.4 against daily core"

---

lib/AppConfig.php
tests/acceptance/features/webUISecureView/main.feature

Fixes https://github.com/owncloud/enterprise/issues/4143
* Upgrade ownCloud CE to 10.5.0 with richdocuments having this patch
The app will keep working as CE. No grace period will be started and no license is needed
* Upgrade ownCloud EE to 10.5.0 with richdocuments having this patch
**admin MUST explicitly set the app as EE**, (see the "expected consequences" section):
```
occ config:app:set richdocuments isEEActive --value yes
```
This could be done before upgrading
* Enabling richdocument's EE features
Run the following command. The grace period will be started and a license will be asked for (normal grace period workflow)
```
occ config:app:set richdocuments isEEActive --value yes
```
* For CE: none. The app will behave normally without any problem
* For EE:
* They should run the `occ …

Hotfix for checking license for a specific feature in richdocuments

---

lib/AppConfig.php
templates/admin.php
tests/acceptance/features/webUISecureView/main.feature
tests/unit/AppConfigTest.php

Add warning for secure view regarding license

---

lib/Db/Wopi.php

This PR extends `access_token_ttl` from 30 minutes to 10 hours which is recommended duration in the following wopi's document:
https://wopi.readthedocs.io/projects/wopirest/en/latest/concepts.html#term-access-token-ttl
In this way, it will help to reduce early token expiration problem mentioned in https://github.com/owncloud/enterprise/issues/4237

expire wopi token after 10 hours as suggested in the project docs

---

lib/Controller/DocumentController.php
phpstan.neon

The latest release of phpstan reports:
```
php -d zend.enable_gc=0 vendor-bin/phpstan/vendor/bin/phpstan analyse --memory-limit=4G --configuration=./phpstan.neon --no-progress --level=5 appinfo lib
⚠️  You're using a deprecated config option bootstrap. ⚠️️
This option has been replaced with bootstrapFiles which accepts a list of files
to execute before the analysis.
------ -------------------------------------------------------------------- 
Line   lib/Controller/DocumentController.php                               
------ -------------------------------------------------------------------- 
78     Comparison operation ">" between int<1, max> and 0 is always true.  
------ -------------------------------------------------------------------- 
[ERROR] Found 1 error …
```

Fix if statement reported by phpstan

---

.drone.star
composer.json
vendor-bin/behat/composer.json

Issue https://github.com/owncloud/core/issues/38067
See issue for details - `behat` acceptance tests need to use PHP  7.4 for the dependencies to sort themselves out with composer 2.0
And adjusting PHP to 7.2 in `composer.json` because owncloud min-version="10.5" anyway, which requires PHP 7.2

Adjust PHP dependencies for composer 2.0

---

lib/AppInfo/Application.php
lib/Controller/DocumentController.php
phpstan.neon
tests/unit/Controller/DocumentControllerTest.php

If the richdocuments app is installed in the custom folder and Use OOXML by default for new files option is enabled, richdocuments app could not create any document from template. This pr fixes explained problem.
Fixes https://github.com/owncloud/enterprise/issues/4281

Fix custom app folder document create problem

---

js/documents.js
lib/Controller/DocumentController.php
lib/Db/Wopi.php
templates/documents.php
tests/unit/Db/WopiTest.php

Wopi protocol suggests returning access_token_ttl value to wopi client. In this way, wopi client can decide what to do when token about to expire. 
For example, collabora warns user when 15 minutes before expire and shows below message to user:
If user still doesn't refresh the session, it warns again periodically in every 2 minutes.
Fixes owncloud/enterprise#4237

pass access token ttl value to wopi client

---

appinfo/info.xml
lib/Controller/DocumentController.php

In OC10.7 we changed logic for encryption events (got rid of legacy hooks listeners [1][2]). This app needs to be adjusted for this change to trigger decryption of master key files
[1] https://github.com/owncloud/encryption/pull/25
[2] https://github.com/owncloud/core/pull/38289

in oc10.7 old hooks were removed for master key encryption

---

README.md
js/admin.js
js/viewer/viewer.js
lib/AppConfig.php
lib/AppInfo/Application.php
lib/Controller/DocumentController.php
lib/Controller/SettingsController.php
templates/admin.php

Fixes: https://github.com/owncloud/enterprise/issues/4578 , https://github.com/owncloud/enterprise/issues/4566
With this change, it will be possible to activate the Setting "Open documents in Secure View with watermark by default".
Due to this change, the file owner can view/edit/export/print a file in secure view mode (With watermark) without sharing the file.

Allow setting default open action with secure-view enforced session for supported documents

---

lib/Controller/DocumentController.php

Before this PR ist was not possible to add comments on PDF files with rich documents/Collabora, this works now.
Fixes: - https://github.com/owncloud/enterprise/issues/4606
Before:
After:

Enable comments on pdfs 

---

lib/Controller/DocumentController.php
tests/unit/Controller/DocumentControllerTest.php

Fixes: https://github.com/owncloud/enterprise/issues/4627

Prevent documents with tabs in filenames / or any other invalid chars from being created 

---

lib/Http/DownloadResponse.php

Fixes #413 
Content-Length is supposed to be a string (a "numeric" string in this case). Explicitly cast the calculated value to string so that `phpstan` does not complain.

Cast content-length number as a string

---

lib/Controller/DocumentController.php

If you create a file via UI Office->New Document, no filename will be set, this will be handled via backend, so we shoud only check the path if filename is given.
Additional add log message on error 'Invalid Path' .

Only verify path if filename is given, additional log error

---

phpunit.xml

This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198

[tests-only][full-ci]Tidy up the phpunit xml file for `Richdocuments` app

---

.drone.star
appinfo/info.xml
lib/Controller/WebAssetController.php

```
$ make test-php-phpstan
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
php -d zend.enable_gc=0 vendor-bin/phpstan/vendor/bin/phpstan analyse --memory-limit=4G --configuration=./phpstan.neon --no-progress --level=5 appinfo lib
------ ------------------------------------------------------------------------------------ 
Line   lib/Controller/WebAssetController.php                                               
------ ------------------------------------------------------------------------------------ 
80     Call to static method …
```

Adjust getMimeType for guzzle7 dependencies

---

.drone.star
.phan/config.php
appinfo/Migrations/Version20190710194710.php
appinfo/routes.php
lib/AppInfo/Application.php
lib/BackgroundJob/CleanupExpiredWopiTokens.php
lib/Controller/DocumentController.php
lib/Db/Storage.php
lib/Http/DownloadResponse.php
lib/Storage.php
vendor-bin/phan/composer.json

`phan` will report errors if any of the code is not compatible with PHP 7.3.
This app still supports PHP 7.3 when used with oC10 core 10.11 and earlier.

[tests-only] [full-ci] Run phan with php 7.3

---

css/style.css

Fixes https://github.com/owncloud/richdocuments/issues/468
Before:
After:

Display .documentslist as inline table

---

phpstan.neon

Now that core has Symfony5, phpstan no longer complains - good.
Fixes #491

[tests-only] [full-ci] Remove Symfony event dispatch from ignoreErrors

---

js/web/richdocuments.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

Replace deprecated String.prototype.substr()

---

appinfo/routes.php
js/documents.js
lib/Controller/DocumentController.php
lib/Controller/FederationController.php
lib/Controller/OCSFederationController.php
lib/Controller/WopiController.php
lib/Db/Wopi.php
lib/DocumentService.php
lib/FederationService.php
lib/FileService.php
tests/unit/Controller/DocumentControllerTest.php
tests/unit/Controller/WopiControllerTest.php
tests/unit/DocumentServiceTest.php
tests/unit/FederationServiceTest.php

implements https://github.com/owncloud/richdocuments/issues/381

Federated shares support v1 

---

js/documents.js

@jvillafanez at least now we know why the comparison operator was needed..... fixes https://github.com/owncloud/richdocuments/issues/514

fix issue with null return

---

appinfo/Migrations/Version20190310162809.php

In preparation of php8.2 support - see https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated
Similar to core https://github.com/owncloud/core/pull/40995

fix: drop usage of ${}

---

lib/AppInfo/Application.php

https://github.com/owncloud/richdocuments/pull/522/files#diff-6301937af1cc1575e9e18ecd27c4a51f0d3cf9ce12e59a14709f626dfa3ef952R28 (first added in richdocuments 4.1.0) introduced a change to the documents.php/index route but https://github.com/owncloud/richdocuments/blob/master/lib/AppInfo/Application.php#L52 was not updated.
As as result, currently on 4.1.0 the `Files->Office` menu is not reachable (icon is there but you get redirected back to the files page).
Related issue: https://github.com/owncloud/enterprise/issues/6349

Update route to documents.php/index
